### ISSUE TITLE
Improve the "pledge" experience

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#112]
As a letter recipient visiting https://votefwd.org/vote, I'm prompted to enter the code from the bottom of my letter, then shown my state election info link, and prompted (as a second step) to "pledge" if I'm so-inclined. See mockup attached.

**Comment by sjforman** [comment]
[pledge-sequence.pdf](https://github.com/sjforman/votefwd/files/2466493/pledge-sequence.pdf)

**Comment by jimwebb** [comment]
When this happens, consider resetting all of the existing pledges. The help desk is getting a fair number of folks saying "oops, I accidentally pledged on behalf of a voter because I wanted to see what would happen if they entered the code."

**Comment by sjforman** [comment]
Good call @jimwebb. Might be worth a quick stopgap change to actually just disable the form in production for now.

**Comment by sjforman** [comment]
#195

**Comment by sjforman** [comment]
Closed by #195.
