### ISSUE TITLE
Many users wind up with multiple accounts

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#173]
Story: As a user who signs or logs in on a subsequent visit after I already have an account using a different method from the way I signed up the first time, but the *same email address*, I get logged into the *same account* rather than a new one.

**Comment by sjforman** [comment]
Two possible shorter term things that would address parts of the problem by, hopefully, preventing it from happening in many cases: 
 
#103 
#214

**Comment by jimwebb** [comment]
Another short-term help might be to allow admins to delete (empty) accounts. We can respond to help-desk queries by removing the extra accounts and telling them which one to log in with. (Not a great solution, because they could still sign up with a duplicate account again.)

**Comment by sjforman** [comment]
I think #214 may have done the trick here. I tested it on production and it stopped me from making a duplicate account. Still need to clean up the historical ones, but fingers crossed it will keep this from happening going forward. Thank you @jeffkole!
