### ISSUE TITLE
Show clearly on the districts display which districts have voters left and which don't!

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#183]
As a user looking at one of the "district" views (either on the homepage or on the district picker), I can see how many voters are still remaining to be adopted, with a special marking for the ones that have 0 left, so I don't accidentally pick one of those. 

Note: currently, the "district" views rely on an endpoint that does, essentially `select * from districts`. So they don't currently have access to stats. But also these pages get loaded a lot, so, maybe we don't want to be hammering the database every time the page is loaded?

**Comment by yoni** [comment]
Sounds like simple stats cacheing can help here (e.g. load the stats at most every 1 minute).

**Comment by sjforman** [comment]
Done via #200
