### ISSUE TITLE
Make the voters appear in a deterministic order in volunteer's lists on the website!

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#186]
Current behavior: Voter records appear in an unpredictable order on `/dashboard` that changes over time as the state of the component changes.

Desired behavior: Voter records appear in chronological order of being "adopted" by the user, i.e., the one adopted farthest in the past appears first.

Notes: 
 *  Because voters are adopted in bundles of 5 and 25, and those are transactions, they will all appear to have been updated at the same instant if you inspect the `adopted_at` field in the database, so, probably will need to order first by `adopted_at` and then by something else...might as well be first name, I guess. 
 * I don't recall what order they appear in when the PDF is generated, but I believe it's deterministic. It would be very very good if the order could be made to be the *same* as the order they appear on the front-end, even if that means changing the logic for ordering in the generated PDF bundle to match this new ordering scheme for the client-side.

Here's an example of a user report of confusion that seems to have resulted from the non-deterministic ordering: 

> hope that scott@votefwd.org reaches a person...
I registered to write to 25 people
Got a listing of 25 people
Clicked on download all, printed out letters for the 50 people who were downloaded.
discovered that none of the 50 names match with the 25 that I can verify writing to or sending to on your site
 If I send the 50.... I have no way to let you know that they have been sent.....  SO....
I will go back to the list of 25 & download them ONE AT A TIME & check off each as written & when mailed.
       I have no idea what to do with the 50 name list...

**Comment by bbrodsky** [comment]
So both the pdf and the voter list were not in a deterministic order. Now they are sorted by adopted_at then by the id.

**Comment by sjforman** [comment]
Closed by #198
