### ISSUE TITLE
Fix description of PA07

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#209]
Putting this here to track it, but this is a DB/content issue, not a code issue.  

PA07's description reads:

![image](https://user-images.githubusercontent.com/1408929/46965475-f7645200-d078-11e8-935d-5d4f639000b5.png)

But it no longer includes Delaware county. (The [Wikipedia entry's](https://en.wikipedia.org/wiki/Pennsylvania%27s_7th_congressional_district) first paragraph is inaccurate.) Here's the old district — Delaware county is way down south: 

![image](https://user-images.githubusercontent.com/1408929/46965959-31822380-d07a-11e8-8bfc-4593baa51191.png)

The new district, created after a gerrymandering case in January '18, looks like this (this is the Vote Forward map, which is correct): 

![image](https://user-images.githubusercontent.com/1408929/46965971-4068d600-d07a-11e8-9928-263e537a901b.png)

I suggest just striking "which includes most of Delaware county."

**Comment by sjforman** [comment]
Good catch! Fixed.
