### ISSUE TITLE
Ensure more errors are processed correctly

### ISSUE THREAD

**Issue by carlmanaster** [sjforman/votefwd#210]
https://voteforward.slack.com/archives/CBMF0K1JT/p1539623317000100

Review all the catch clauses and make sure they do the right thing, ultimately something which calls res.end().  Include necessary client- and server- side logging.

Ensure there _are_ catch clauses, too!

**Comment by carlmanaster** [comment]
Changed from "all" to "more" because I think it might be more realistic.  I'm going to try to reduce the number of warnings like

> Warning: a promise was created in a handler at Users/carlmanaster/code/politics/votefwd/server/userService.js:163:10 but was not returned from it, see http://goo.gl/rRqMUw


by adding res.end() and similar bits to catch clauses.

**Comment by sjforman** [comment]
Done in #231 — thank you!
