### ISSUE TITLE
Make district stats view performant

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#211]
Currently the `/` has the district stats commented out for performance reasons. 

Todo: figure out a way to turn them back on that is performant. 

Possibilities: 
 * `mem`
 * psql materialized views?

**Comment by jeffkole** [comment]
What was the reasoning behind the view versus just doing a regular query?

**Comment by carlmanaster** [comment]
I'm new to knex, and the view seemed like an easy way to make the change with minimal knex wrangling.  And views, in my experience, are performant and lightweight, so I didn't anticipate any bad consequences from their use.  I don't believe views, per se, are the problem; we're just (I think) trying to ask a relatively costly question too frequently.

**Comment by jeffkole** [comment]
Yes, I get that, and the view is likely not the performance issue.  While views are handy, they hide logic details in the database, which makes it hard to keep them up to date with other changes.  The same code used to generate the view (specifically `db.raw()`) could be used to run the query the view runs whenever the endpoint it called.

**Comment by sjforman** [comment]
@jeffkole what do you think? Does that sound like a reasonable approach to you?

**Comment by jeffkole** [comment]
Do we have timings on the queries from the view?  I can't imagine the query is so complex that it is actually a performance issue.  There's just not *that* much data.  It looked like the error was on acquiring a connection, not on running the query, which would point to the query not being the actual problem.  So, while the proposed solution would work, I don't know that it would necessarily fix the underlying problem.  If @asterns has time, I think it would be better spent nailing down the core problem, but he can always put in the workaround and see if that lets us get the data back up to the users for the time being.

**Comment by carlmanaster** [comment]
@jeffkole Would that be solved by https://github.com/sjforman/votefwd/issues/210 ?

**Comment by jeffkole** [comment]
Another option is to rewrite the view so that it doesn't do the union with a nested loop over the `voters` table.

```
select d.district_id, d.state, d.description, sum(case when v.id is not null and adopter_user_id is null then 1 else 0 end) as available_voter_count
from   districts d
left outer join   voters    v on v.district_id = d.district_id and  v.adopter_user_id is null
group by d.district_id, d.state, d.description
```

An index on `(district_id, adopter_user_id)` on the `voters` table would help, too.

**Comment by asterns** [comment]
We should definitely add those indexes regardless, didn't realize they weren't there. I'll do that tonight. I still think the denormalized approach is safer and will result in lower overall strain on the DB. It's also relatively hard to test the performance of the view without loading tons of voters into a test db, or testing against production.

**Comment by asterns** [comment]
But I could be convinced to do the view approach if you feel strongly

**Comment by asterns** [comment]
On second look, I don't think and index on `(district_id, adopter_user_id)` on the `voters` table would actually help, especially if we go with the denormalized approach, but even if we go with the view.  The view query is looking for `adopter_user_id is null` which I believe would not register with an index.  There's already an index on `district_id` so the denormalization should be plenty fast already.
