### ISSUE TITLE
"Generate Bundle" in admin screens downloads wrong PDF

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#213]
This bug is happening in the backend admin screens, when generating a PDF bundle on behalf of a volunteer.

To reproduce: 
1. Log in as an admin and view a user (for instance, https://votefwd.org/admin/user/auth0%7C5bba6642ea4644072b1b0c07 )
2. Click "Generate Bundle" for adopted voters: 
![image](https://user-images.githubusercontent.com/1408929/46974353-d0664a00-d091-11e8-9336-cd34048ab0a2.png)

The resulting PDF is the list of your adopted voters (you, the logged in admin — not the user you're trying to download a bundle for). Verify by checking your own list or by downloading a different user's bundle. 

Obviously the PDF should be the of the volunteer in question, not the logged-in admin.

**Comment by sjforman** [comment]
@asterns could you take a look at this one? I attempted, but I think you might be able to do it faster since it interacts with the changes to fix the iOS download problem. Relevant client-side file: `/src/admin/AdminUser.js`. I double-checked to verify that the user id of the user being acted-upon is being passed to the server in a call to the (I suppose now properly deprecated) `/downloadAllLetters` endpoint. But it wasn't quickly obvious to me how to pass it down into the voter service and deal with the JWT.

**Comment by sjforman** [comment]
Or @carlmanaster if you have time today!

**Comment by asterns** [comment]
@carlmanaster - looks like you took this.  I think my previous iPad fix likely broke this.  The fix could be to change `server.js`
Right now, it does:
```
    voterService.downloadAllLetters(req.user.sub, downloadFileCallback(res));
```
By looking at `req.user.sub` it makes sure a user couldn't pass in an arbitrary `user_id` and download their files (something that the old code made it possible to do).  But it breaks this admin functionality.  One way to fix would be to add a new endpoint for this admin use case (e.g. something like) 

```
router.route('/voters/downloadAllLettersForUser')
  .get(checkJwt, checkAdmin, function(req, res) {
    voterService.downloadAllLetters(req.query.user_id, downloadFileCallback(res));
  });
```
and then point the code in `/src/admin/AdminUser.js` to that new endpoint.

**Comment by carlmanaster** [comment]
Thanks, @asterns .  Yes; I made the change to use req.query.user_id directly in the existing endpoint and it solved the problem for admins - but I was concerned it might break something else.  I like the idea of a separate endpoint and will implement it.

**Comment by sjforman** [comment]
Done via #215
