### ISSUE TITLE
Warn users who are trying to create a second account with an email address we already have in db?

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#214]
Possibly an easier/faster way than #173 to get us part of the way there.

**Comment by jeffkole** [comment]
Yes, definitely faster.

**Comment by sjforman** [comment]
https://github.com/sjforman/votefwd/compare/214-warn-users-upon-second-account-creation?expand=1

**Comment by sjforman** [comment]
Addressed by #229
