### ISSUE TITLE
Set up SPF records for MailChimp, responder emails

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#238]
The domain votefwd.org has no SPF records configured -- this may be why some folks are reporting that they're not getting emails. (They're going into their spam filters.) 

SPF records for the domain should be configured for both MailChimp bulk emails and for verification emails. I can validate that they're failing the SPF check right now:

![image](https://user-images.githubusercontent.com/1408929/47269994-4e639e80-d533-11e8-857d-c1a711601ace.png)

To fix: 
- Instructions for MailChimp: https://mailchimp.com/help/set-up-custom-domain-authentication-dkim-and-spf/
- For Verification emails (Amazon SES): https://docs.aws.amazon.com/ses/latest/DeveloperGuide/spf.html

**Comment by sjforman** [comment]
Just added: 

![screenshot 2018-10-21 12 16 25](https://user-images.githubusercontent.com/2543151/47271193-2ff9a500-d52b-11e8-8e2c-416caabeabd2.png)

**Comment by sjforman** [comment]
@jimwebb could you test this again when you have a moment? (I did change the refresh time from 1 hour to 10 minutes, so, could test again in another 10+ min). Thank you!

**Comment by sjforman** [comment]
Fixed, I think: 

![screenshot 2018-10-21 12 51 50](https://user-images.githubusercontent.com/2543151/47271632-20c92600-d530-11e8-9ef5-24849ff88535.png)

**Comment by sjforman** [comment]
Done! Thank you
