### ISSUE TITLE
"Relinquish all unprepped"

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#252]
As a Vote Forward admin, I can click a "release all unprepped voters" button on a volunteer's admin detail page, so all their not-yet-prepped voters are released back into the pool to be adopted by other volunteers. 

Note: 

 * This would be separate and distinct from the "relinquish bundle" button that's available for any bundle in which no voters have been marked "prepped." 
 * This maybe perhaps should have an "are you sure you want to do this?" speedbump.

**Comment by jimwebb** [comment]
Duplicate of https://github.com/sjforman/votefwd/issues/226; I'll close that one and leave this one open.

**Comment by sjforman** [comment]
@carlmanaster this is the other one where we could really use your help at the moment, if you're willing and able.

**Comment by carlmanaster** [comment]
I'll take a look.

**Comment by sjforman** [comment]
closed by #276 and #279
