### ISSUE TITLE
Abstract the "send" date out of the application 

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#256]
Right now, October 30 is hardcoded in the application; once the server clock hits that date, letters can be moved to the "sent" column. 

The task is to abstract this out of the application — probably into an environment variable — so that developers can test/build the October 30 experience without needing to change their server clocks. :)

**Comment by asterns** [comment]
I referenced a new environment variable in `voterService.js` called `DATE_TO_ENABLE_PLEDGE` that could probably be used for this purpose. It was used in this case for exactly the same reason: to enable testing.

**Comment by jimwebb** [comment]
Opened a PR for this: https://github.com/sjforman/votefwd/pull/263

**Comment by sjforman** [comment]
Closed by #263
