### ISSUE TITLE
On October 30, close all districts to new adoptions

### ISSUE THREAD

**Issue by jimwebb** [sjforman/votefwd#257]
On the "send" date (October 30), we want volunteers to focus on sending their letters, not adopting new voters. 

A proposed solution is to "close" all districts from new voter adoption on that date, either by marking them as full or with an appropriate message (e.g., "Voter adoption is now closed" rather than "All voters adopted"). 

This change will likely have UI repercussions; we may want to hide or de-emphasize the adoption controls. 

The Mississippi special election happening *after* November 7 is a twist; @sjforman will need to weigh in on how that should happen. One option is to leave MS open with a special message; or, shut everything down until November 7 and then reopen MS.

**Comment by jimwebb** [comment]
I think the easiest solution, at least for this election cycle, to build is a single flag that "locks down" the entire site — no new adoptions at all. It makes for the easiest changes to the UI (to really focus folks on sending letters). If that doesn't totally screw up plans for Mississippi, I'll start there. Does that sound okay?

**Comment by jimwebb** [comment]
I started copy changes here: https://github.com/sjforman/votefwd/pull/269 -- this PR doesn't actually disable district adoption (yet) but changes the copy to remove the "Switch Districts" link.

**Comment by sjforman** [comment]
(Done via #263)
