### ISSUE TITLE
Pre-fill NVRA form

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#356]
# Story 

As a Vote Forward volunteer writing "voter registration" letters to some state, when I generate an individual PDF for a prospective voter, or a batch of PDFs for many such voters to print out and send to that prospective voter, the file includes pre-filled voter registration form(s) that each recipient can transmit to the appropriate state authority to get registered to vote.

# Notes 

* We will want to also have the ability to use state-specific forms, but we will likely use the NVRA form in many scenarios, so we're starting here. 
* Which parts of the registration form are allowed to be pre-filled varies by state, and which parts are advisable to pre-fill will vary based on the targeting of the campaign. So, important to be able to configure on a campaign-specific basis which fields are pre-filled.

**Comment by jlev** [comment]
Added initial form profile functionality and tests in bb7b8ce0d1294f3210c0880a1cd34656127f1a9c

Which fields will need to be configurable on a state basis? Should that be a new field on `districts`, or would you prefer a new table to join to it? Could also be hard-coded, if you know in advance which states allow which fields.

**Comment by sjforman** [comment]
Awesome. Got it working locally, after some futzing with getting pdftk server installed properly. Seems like maybe it's not super-well maintained? But it does work. 

Re: pre-filling fields, I don't know in great detail yet, but I think it's knowable in advance and changes infrequently, so hard-coding somewhere seems entirely reasonable to me for first pass.

**Comment by sjforman** [comment]
A bit more info on the plan for June w.r.t. pre-filling. The goal is to launch in 6 states:

 * WI — not sure yet what should be pre-filled
 * FL — will want to pre-fill first name, middle initial, last name, address, city, zip, county
 * TX — prefilling forms is currently technically legal, but evidently about to become illegal, so out of abundance of caution, we'll refrain
 * MI — will want to pre-fill first name, middle initial, last name, address, city, zip
 * GA — will want to pre-fill first name, middle initial, last name, address, city, zip, county
 * AZ — will want to pre-fill first name, middle initial, last name, address, city, zip

**Comment by jlev** [comment]
County isn't a field on the NVRA form, but it might be on those state specific ones... 

Do you get county from your data sources, or is that something we should build in a geocode step for on import? I'm partial to http://geocod.io for cost and simplicity, but can also do SmartyStreets or google if you prefer.

**Comment by sjforman** [comment]
Right — yes — some of the state ones ask for it. & we do get it from TargetSmart. Not currently / yet stored in database, so will have to do a little work to expose it, but we do have it.
