### ISSUE TITLE
Apply ShareMail postage

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#357]
# Story

As a Vote Forward volunteer writing "voter registration" letters to some state, when I generate an individual PDF for a prospective voter, or a batch of PDFs for many such voters to print out and send to that prospective voter, the file includes a cover sheet with all the required USPS stuff — postage, indicia, etc. — so it can be folded-over and taped closed to be sent back to the appropriate state authorities.

# Notes

 * We'll be using a USPS product called "ShareMail" to pre-pay the return postage.
 * Still an open question as to whether this will be permitted, so we're holding off on this one until we have confirmation. 

# Elements of the mail piece

 * Unique for each recipient: the return address and the "intelligent mail barcode." 
 * Unique for a recipient in a county: the destination address.
  * In some states, the technically correct thing to do is to send to the appropriate county registrar. This likely only matters at high volume, but might as well get it right at the outset if we have the luxury of customizing each return piece.
 * Static: the other postage markings.

**Comment by jlev** [comment]
Some states request that users mail their forms to a county election official. I gathered these for NY at https://github.com/fightforthefuture/votebot-forms/tree/master/app/pdf_forms/data, but I see that Florida also has a list in their state registration PDF. May need to check for every state where we're customizing the form.

Google Civic Info API does claim to have this info under `state[].electionAdministrationBody.correspondenceAddress`, but that's not consistently returning data for me with test addresses. https://developers.google.com/civic-information/docs/v2/elections/voterInfoQuery (using electionId 2000 to test)
