### ISSUE TITLE
Pre-fill State-specific form

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#358]
# Story

As a Vote Forward volunteer writing "voter registration" letters to some state, when I generate an individual PDF for a prospective voter, or a batch of PDFs for many such voters to print out and send to that prospective voter, the file includes pre-filled voter registration form(s) *for that state* that each recipient can transmit to the appropriate state authority to get registered to vote.

# Notes

* This is a step 2 following #356

**Comment by jlev** [comment]
Looks like the official PDF in English is https://dos.myflorida.com/media/693757/dsde39.pdf

**Comment by jlev** [comment]
More state forms:

GA: https://registertovote.sos.ga.gov/GAOLVR/images/reg_form.pdf
WI: https://elections.wi.gov/sites/default/files/publication/154/el_131_voter_registration_application_pdf_23730.pdf
TX: https://www.sos.state.tx.us/elections/forms/vr-with-receipt.pdf
MI: https://www.michigan.gov/documents/MIVoterRegistration_97046_7.pdf
AZ: https://azsos.gov/sites/default/files/voter_registration_form.pdf (en and es)

**Comment by jlev** [comment]
Added code to prefill PDF forms for FL, GA and WI and match field names from state.

Other state PDFs do not include fillable form layouts; we will need to modify the files provided.
