### ISSUE TITLE
Bug: collating of mixed-type campaign PDFs

### ISSUE THREAD

**Issue by sjforman** [sjforman/votefwd#395]
Current behavior: As a volunteer, if I adopt voters from two campaigns of different types — one with registration forms and one without — so, for example, a `gotv` or `vrbm` campaign and a `vrbm-form` or `vrbm-no9` campaign — and download a file that contains both types of letters, the voter registration forms appear first, alongside mis-matched non-registration-form-voters.

Expected behavior: The forms should appear adjacent to the correct voters. 

Steps to reproduce using a fresh dev database with current seed data: 
 
 * Update the election date for a GOTV campaign to place it in the future: `update districts set election_date='2021-04-02' where district_id='WISCOURT';`
 * Update the FL campaign to be of type `vrbm-form`: `update districts set type='vrbm-form' where district_id='FLVRBM1';` (this should probably change in the seed data as well)
 * Log in and select the `gotv` campaign as your current campaign on the dashboard. 
 * Adopt 5 voters. 
 * Switch to the `vrbm-form` campaign on the dashboard. 
 * Adopt 5 more voters. 
 * Download file. 
 * Observe mis-ordering. 

Notes: 
 * If the easiest way to address this is to force VRBM campaigns with registration forms to always appear *first* that's fine. 
 * A backstop solution if this winds up being very complicated to fix would be to prevent such situations from occurring in the first place. Hoping that won't be necessary though.

**Comment by jlev** [comment]
Turns out the easiest way to fix this and ensure the ordering is consistent in the web UI is to enforce it in SQL. Tested locally, and it works for adopted groups with mixed campaign types.
